before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y gfortran
  - export FC=gfortran

before_script:
  - cd data
  - ./get_nndc_data.py --batch
  - export CROSS_SECTIONS=$PWD/nndc/cross_sections.xml
  - cd ..

script:
  - cd tests
  - ./run_tests.py -C "basic-debug" -j 4
  - cd ..
