before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran
  - export FC=gfortran

before_script:
  - cd data
  - ./get_nndc_data.py
  - export CROSS_SECTIONS=$PWD/nndc/cross_sections.xml
  - cd ..
  - echo $CROSS_SECTIONS
  - ls $CROSS_SECTIONS
